/**
 * Carts
 *
 * Create a cart using BigCommerce cart logic.
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.petedoyle.snappy.common.api.bigcommerce.carts.v3.model

import dev.petedoyle.snappy.common.api.bigcommerce.carts.v3.model.BaseItemCouponsCouponCode

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Required in a /POST request.
 *
 * @param couponCode 
 */
@JsonClass(generateAdapter = true)
data class BaseItemCoupons (

    @Json(name = "coupon_code")
    val couponCode: BaseItemCouponsCouponCode

)

